---
apiVersion: v1
kind: Namespace
metadata:
  name: nextopus
  labels:
    app.kubernetes.io/name: nextopus
    app.kubernetes.io/part-of: nextopus-platform
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: nextopus-system
  labels:
    app.kubernetes.io/name: nextopus-system
    app.kubernetes.io/part-of: nextopus-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/name: observability
    app.kubernetes.io/part-of: nextopus-platform
